openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /token-auth/:
    post:
      operationId: CreateJSONWebToken
      description: 'API View that receives a POST with a user''s username and password.


        Returns a JSON Web Token that can be used for authenticated requests.'
      parameters: []
      requestBody:
        content:
          application/json:
            schema: &id001
              properties:
                username:
                  type: string
                password:
                  type: string
                  writeOnly: true
              required:
              - username
              - password
          application/x-www-form-urlencoded:
            schema: *id001
          multipart/form-data:
            schema: *id001
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  username:
                    type: string
                required:
                - username
          description: ''
