# Generated by Django 3.0.8 on 2020-08-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
