# Generated by Django 3.0.8 on 2020-08-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
