# Generated by Django 3.0.8 on 2020-08-09 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Classroom', '0003_auto_20200809_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='event',
            new_name='events',
        ),
    ]
