# Generated by Django 3.0.8 on 2020-08-09 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Classroom', '0004_auto_20200809_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='events',
            new_name='event',
        ),
    ]
